stages:
  - build
  - test

workflow:
  rules:
    # Run pipeline for GitHub PRs to dev (does not support PRs from forks)
    - if: $CI_PIPELINE_SOURCE == "external_pull_request_event" && $CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_NAME == "dev"
    - if: $CI_PIPELINE_SOURCE == "external_pull_request_event" && $CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_NAME == "main"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_REF_PROTECTED == "true"
    # Run pipeline if manually triggered via API or web GUI
    - if: $CI_PIPELINE_SOURCE == "api"
    - if: $CI_PIPELINE_SOURCE == "web"

.load-modules:
  before_script:
    - ml vis/Graphviz/8.1.0-GCCcore-12.3.0
    - ml fpga
    - ml xilinx/xrt/2.14
    - ml devel/Doxygen/1.9.5-GCCcore-12.2.0
    - ml compiler/GCC/12.2.0
    - ml devel/CMake/3.24.3-GCCcore-12.2.0

build-dependencies:
  id_tokens:
    CI_JOB_JWT:
      aud: https://git.uni-paderborn.de
  stage: build
  variables:
    #SCHEDULER_PARAMETERS: "-A hpc-prf-ekiapp -p normal -t 2:00:00 -N 1 -n 1 --cpus-per-task=128"
    SCHEDULER_PARAMETERS: "-A hpc-prf-ekiapp -p hacc -t 2:00:00"
  extends: .load-modules
  script:
    - ./buildDependencies.sh
  artifacts:
    paths:
      - "deps/"
    expire_in: 1 week

build-unittests:
  id_tokens:
    CI_JOB_JWT:
      aud: https://git.uni-paderborn.de
  stage: build
  needs:
    - build-dependencies
  variables:
    #SCHEDULER_PARAMETERS: "-A hpc-prf-ekiapp -p normal -t 2:00:00 -N 1 -n 1 --cpus-per-task=128"
    SCHEDULER_PARAMETERS: "-A hpc-prf-ekiapp -p hacc -t 2:00:00"
  extends: .load-modules
  script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make -j $procs
  artifacts:
    paths:
      - "build/"
    expire_in: 1 week

build-integrationtests:
  id_tokens:
    CI_JOB_JWT:
      aud: https://git.uni-paderborn.de
  stage: build
  needs:
    - build-dependencies
  variables:
    #SCHEDULER_PARAMETERS: "-A hpc-prf-ekiapp -p normal -t 2:00:00 -N 1 -n 1 --cpus-per-task=128"
    SCHEDULER_PARAMETERS: "-A hpc-prf-ekiapp -p hacc -t 2:00:00"
  extends: .load-modules
  script:
    - mkdir build-host-mem && cd build-host-mem
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make Integrationtests -j $procs
    - cd ..
    - mkdir build-no-host-mem && cd build-no-host-mem
    - cmake -DCMAKE_BUILD_TYPE=Release -DFINN_USE_HOST_MEM=OFF ..
    - make Integrationtests -j $procs
  artifacts:
    paths:
      - "build-host-mem/"
      - "build-no-host-mem/"
    expire_in: 1 week

lint:
  id_tokens:
    CI_JOB_JWT:
      aud: https://git.uni-paderborn.de
  stage: test
  variables:
    #SCHEDULER_PARAMETERS: "-A hpc-prf-ekiapp -p normal -t 0:30:00 -N 1 -n 1 --cpus-per-task=2 --mem-per-cpu=2G"
    SCHEDULER_PARAMETERS: "-A hpc-prf-ekiapp -p hacc -t 2:00:00"
  script:
    - ml lang
    - ml Python/3.10.4-GCCcore-11.3.0
    - command -v clang-format >/dev/null 2>&1 || pip3 install --user clang-format
    - find ./src \( -name \*.cpp -o -name \*.h -o -name \*.hpp \) -print0 | xargs -0 -n 1 /pc2/users/e/ekiappci/.local/bin/clang-format -style=file --Werror -n --verbose
    - find ./unittests \( -name \*.cpp -o -name \*.h -o -name \*.hpp \) -print0 | xargs -0 -n 1 /pc2/users/e/ekiappci/.local/bin/clang-format -style=file --Werror -n --verbose
    - find ./benchmarks \( -name \*.cpp -o -name \*.h -o -name \*.hpp \) -print0 | xargs -0 -n 1 /pc2/users/e/ekiappci/.local/bin/clang-format -style=file --Werror -n --verbose

run-unittests:
  id_tokens:
    CI_JOB_JWT:
      aud: https://git.uni-paderborn.de
  stage: test
  dependencies:
    - build-unittests
    - build-dependencies
  variables:
    #SCHEDULER_PARAMETERS: "-A hpc-prf-ekiapp -p normal -t 0:30:00 -N 1 -n 1 --cpus-per-task=2 --mem-per-cpu=2G"
    SCHEDULER_PARAMETERS: "-A hpc-prf-ekiapp -p hacc -t 2:00:00"
  extends: .load-modules
  script:
    - cd build
    - ctest --output-on-failure --output-junit ctest-results.xml
  artifacts:
    paths:
      - build/ctest-results.xml
    expire_in: 1 week
    reports:
      junit: build/ctest-results.xml


run-integrationtests:
  id_tokens:
    CI_JOB_JWT:
      aud: https://git.uni-paderborn.de
  stage: test
  dependencies:
    - build-integrationtests
    - build-dependencies
  variables:
    SCHEDULER_PARAMETERS: "-A hpc-prf-ekiapp -p hacc  -t 0:30:00"
  before_script:
    - ml reset
    - ml fpga
    - ml xilinx/xrt/2.16
    - ml xilinx/u55c/u55c_gen3x16_xdma_3_202210_1
    - ml compiler GCC/13.2.0
  script:
    # Reset FPGAs and setup Host Memory Access
    - xbutil reset -d 0000:c1:00.1
    - xbutil reset -d 0000:81:00.1
    - sudo /opt/software/FPGA/scripts/u280/host_memory/enable_hostmem_single_fpga.sh 0000:c1:00.1
    - /opt/software/FPGA/scripts/u280/host_memory/verify_single_fpga.sh 0000:c1:00.1
    - sudo /opt/software/FPGA/scripts/u280/host_memory/enable_hostmem_single_fpga.sh 0000:81:00.1
    - /opt/software/FPGA/scripts/u280/host_memory/verify_single_fpga.sh 0000:81:00.1

    # Test Synchronous Inference with Host memory
    - cd example_networks/jet-structure-classification-with-host-mem
    - ./../../build-host-mem/SyncInference

    # Reset FPGAs again
    - xbutil reset -d 0000:c1:00.1
    - xbutil reset -d 0000:81:00.1

    # Test Synchronous Inference without Host memory
    - cd example_networks/jet-structure-classification-without-host-mem
    - ./../../build-no-host-mem/SyncInference

    # TODO: Run regression tests + asynchronous inference

