// THIS FILE IS AUTOGENERATED BY THE FINN COMPILER

#ifndef FINNDRIVERUSEDDATATYPES
#define FINNDRIVERUSEDDATATYPES

#include <FINNCppDriver/core/BaseDriver.hpp>
#include <FINNCppDriver/utils/FinnDatatypes.hpp>

using InputFinnType = Finn::DatatypeInt<5>;
using OutputFinnType = Finn::DatatypeInt<5>;

namespace Finn {
    template<bool SynchronousInference>
    using Driver = Finn::BaseDriver<SynchronousInference, InputFinnType, OutputFinnType>;
}  // namespace Finn


#endif  // FINNDRIVERUSEDDATATYPES
