import os
from pathlib import Path
from onnx import load
import onnx.numpy_helper as np_helper

scriptFolder = os.path.dirname(os.path.realpath(__file__))
scriptFolder = Path(scriptFolder)

cppDriverRoot = scriptFolder.parent

intermediateModelsFolder = None

for folder in cppDriverRoot.parents:
    for dirs in folder.iterdir():
        if dirs.is_dir() == False:
            continue
        if dirs.name == "intermediate_models":
            intermediateModelsFolder = dirs
            break
        
if intermediateModelsFolder is None:
    raise Exception("Could not find intermediate-models folder in the parent directories.")

dataflowParent = intermediateModelsFolder / "dataflow_parent.onnx"

with open(dataflowParent, "rb") as f:
    onnx_model = load(f)
    

if len(onnx_model.graph.node) != 4:
    raise Exception("The dataflow_parent.onnx model does not have the expected number of nodes (4).")

if (onnx_model.graph.node[0].op_type != "MultiThreshold"):
    raise Exception("The first node in the dataflow_parent.onnx model is not a MultiThreshold node.")

if (onnx_model.graph.node[1].op_type != "StreamingDataflowPartition"):
    raise Exception("The second node in the dataflow_parent.onnx model is not a StreamingDataflowPartition node.")

if (onnx_model.graph.node[2].op_type != "Mul"):
    raise Exception("The third node in the dataflow_parent.onnx model is not a Mul node.")

if (onnx_model.graph.node[3].op_type != "Add"):
    raise Exception("The fourth node in the dataflow_parent.onnx model is not an Add node.")

thresholds = onnx_model.graph.node[0].input[1]

initializer = onnx_model.graph.initializer
init_names = [x.name for x in initializer]

init_ind = init_names.index(thresholds)
ret = np_helper.to_array(onnx_model.graph.initializer[init_ind])
threshold = ret[0]
if (threshold != ret[1]).any():
    raise Exception("Channelwise thresholds are not supported!")

thresholdString= ",".join([str(x)+"f" for x in threshold])

scaler = onnx_model.graph.node[2].input[1]
init_ind = init_names.index(scaler)
scaling_val = np_helper.to_array(onnx_model.graph.initializer[init_ind])

add = onnx_model.graph.node[3].input[1]
init_ind = init_names.index(add)
add_vec = np_helper.to_array(onnx_model.graph.initializer[init_ind])

addVecString= ",".join([str(x)+"f" for x in add_vec])

cppHeader = f"""
// This file is auto-generated by generateQuantHeader.py
// Do not edit this file manually.

#ifndef QUANTIZATION_HEADER
#define QUANTIZATION_HEADER

#include <array>

constexpr std::array<float, 255> thresholds = {{{thresholdString}}};

constexpr std::array<float, 5> addVec = {{{addVecString}}};

constexpr float scalingValue = {scaling_val}f;

#endif // QUANTIZATION_HEADER
"""

with open(cppDriverRoot / "hostParameters.h", "w") as f:
    f.write(cppHeader)