// THIS FILE IS AUTOGENERATED BY THE FINN COMPILER
#include "../core/BaseDriver.hpp"
#include "../utils/FinnDatatypes.hpp"

using InputFinnType = Finn::DatatypeInt<2>;
using OutputFinnType = Finn::DatatypeBinary;

namespace Finn {
    template<bool SynchronousInference>
    using Driver = Finn::BaseDriver<SynchronousInference, InputFinnType, OutputFinnType>;
}  // namespace Finn