// THIS FILE IS AUTOGENERATED BY THE FINN COMPILER

#ifndef FINNDRIVERUSEDDATATYPES
#define FINNDRIVERUSEDDATATYPES
#include "../core/BaseDriver.hpp"
#include "../utils/FinnDatatypes.hpp"

using InputFinnType = Finn::DatatypeInt<8>;
using OutputFinnType = Finn::DatatypeInt<16>;

namespace Finn {
    template<bool SynchronousInference>
    using Driver = Finn::BaseDriver<SynchronousInference, InputFinnType, OutputFinnType>;
}  // namespace Finn


#endif  // FINNDRIVERUSEDDATATYPES
